In [ ]:
from src.preprocess.parquet_preprocessor import ParquetPreprocessor

ParquetPreprocessor.csv_to_parquet("data/raw/active_alarms_prod.csv", "data/raw/active_alarms_prod.parquet")

In [1]:
import polars as pl
from dotenv import load_dotenv
import os

load_dotenv(".env")

from src.repository.alarm_graph_repository import AlarmGraphRepository

lazy_frame = pl.scan_parquet("data/raw/active_alarms_prod.parquet")
graph_repo = AlarmGraphRepository(os.getenv("ACTIVE_DB_PATH"))

In [2]:
from src.pipelines.simple_time_correlation import SimpleTimeCorrelationActive

SimpleTimeCorrelationActive.train(lazy_frame, graph_repo)

ccccc

Processando nós:   0%|          | 0/866 [00:00<?, ?nó/s]

ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2004 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff

Processando nós:   1%|          | 8/866 [00:02<02:51,  4.99nó/s]

ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=106 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=13 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=60 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=399 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=264 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=67 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=32 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=237 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=9 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=32 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff

Processando nós:   3%|▎         | 27/866 [00:02<00:38, 21.96nó/s]

ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=14 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=29 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=60 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=36 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=38 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=60 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=32 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=7 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=40 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff

Processando nós:   5%|▌         | 46/866 [00:02<00:19, 41.34nó/s]

ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=43 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=163 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=35 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=27 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=33 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=62 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=162 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff

Processando nós:   7%|▋         | 64/866 [00:02<00:14, 54.99nó/s]

ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=25 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=114 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=27 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=57 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=27 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=13 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=28 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=27 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff

Processando nós:  10%|█         | 87/866 [00:03<00:09, 78.06nó/s]

ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=33 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=7 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=7 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=44 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=64 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=32 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=50 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  12%|█▏        | 107/866 [00:03<00:09, 81.83nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=16 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=10 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=7 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=38 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=9 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=27 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=13 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=15 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=33 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  14%|█▎        | 118/866 [00:03<00:08, 88.74nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=32 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=27 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=39 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff

Processando nós:  16%|█▌        | 138/866 [00:03<00:09, 77.93nó/s]

ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=12 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=33 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=32 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=16 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=16 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=27 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff

Processando nós:  18%|█▊        | 156/866 [00:03<00:09, 78.38nó/s]

ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=27 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=19 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=32 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=28 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=8 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=7 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  19%|█▉        | 166/866 [00:03<00:08, 82.46nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=19 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=33 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff

Processando nós:  21%|██▏       | 186/866 [00:04<00:08, 83.70nó/s]

ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=14 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=26 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  23%|██▎       | 203/866 [00:04<00:08, 73.86nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=8 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=10 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=7 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  26%|██▌       | 221/866 [00:04<00:08, 80.12nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=8 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=22 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  27%|██▋       | 233/866 [00:04<00:07, 88.17nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=9 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=15 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=9 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  29%|██▉       | 254/866 [00:05<00:06, 92.10nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  32%|███▏      | 276/866 [00:05<00:06, 94.24nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=16 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=8 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=7 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  33%|███▎      | 286/866 [00:05<00:06, 89.81nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=14 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  35%|███▌      | 305/866 [00:05<00:07, 79.77nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=9 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff

Processando nós:  38%|███▊      | 326/866 [00:05<00:06, 88.61nó/s]

ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  40%|████      | 350/866 [00:06<00:05, 98.62nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  43%|████▎     | 371/866 [00:06<00:04, 100.62nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  46%|████▌     | 399/866 [00:06<00:04, 116.60nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=13 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  49%|████▉     | 425/866 [00:06<00:03, 121.49nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=6 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff

Processando nós:  52%|█████▏    | 450/866 [00:06<00:03, 114.70nó/s]

ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff

Processando nós:  53%|█████▎    | 462/866 [00:07<00:03, 107.88nó/s]

ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  56%|█████▌    | 487/866 [00:07<00:03, 108.72nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=7 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  59%|█████▉    | 509/866 [00:07<00:03, 92.24nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  60%|█████▉    | 519/866 [00:07<00:03, 87.74nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff

Processando nós:  62%|██████▏   | 539/866 [00:07<00:03, 92.63nó/s]

ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=5 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Processando nós:  65%|██████▌   | 564/866 [00:08<00:03, 99.03nó/s]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=3 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=2 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=4 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]
insert ok
eeeeeee
ffffffff
ddddd
[pid=9886] con id: 133714266642736 | path: ./volumes/graph_active.db
Datetime(time_unit='us', time_zone=None)
Datetime(time_unit='us', time_zone=None)
gggg
antes do insert | rows=1 | dtypes=[String, String, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None)]

Error: KeyboardInterrupt: <EMPTY MESSAGE>

At:
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/polars/dataframe/frame.py(1795): to_arrow
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/polars/_utils/deprecation.py(128): wrapper
  /home/luiz-felipe/Documents/vertis/alarm_correlation/src/repository/alarm_graph_repository.py(69): save_alarm_nodes
  /home/luiz-felipe/Documents/vertis/alarm_correlation/src/pipelines/simple_time_correlation.py(29): internal_process
  /home/luiz-felipe/Documents/vertis/alarm_correlation/src/pipelines/simple_time_correlation.py(40): train
  /tmp/ipykernel_9886/1828789021.py(3): <module>
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py(3748): run_code
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py(3688): run_ast_nodes
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py(3447): run_cell_async
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/IPython/core/async_helpers.py(128): _pseudo_sync_runner
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py(3225): _run_cell
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py(3170): run_cell
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/ipykernel/zmqshell.py(663): run_cell
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/ipykernel/ipkernel.py(464): do_execute
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/ipykernel/kernelbase.py(834): execute_request
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/ipykernel/ipkernel.py(372): execute_request
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/ipykernel/kernelbase.py(478): dispatch_shell
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/ipykernel/kernelbase.py(621): shell_main
  /usr/lib/python3.12/asyncio/events.py(88): _run
  /usr/lib/python3.12/asyncio/base_events.py(1987): _run_once
  /usr/lib/python3.12/asyncio/base_events.py(641): run_forever
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/tornado/platform/asyncio.py(211): start
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/ipykernel/kernelapp.py(758): start
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/traitlets/config/application.py(1082): launch_instance
  /home/luiz-felipe/Documents/vertis/alarm_correlation/alarm-correlation-venv/lib/python3.12/site-packages/ipykernel_launcher.py(18): <module>
  <frozen runpy>(88): _run_code
  <frozen runpy>(198): _run_module_as_main

In [3]:
from src.postprocess.enumerate_incidents import EnumerateIncidents

EnumerateIncidents.enumerate_data(graph_repo)

graph_repo.preview_nodes()

shape: (20, 6)
┌────────────────────┬────────────────────┬───────────────────┬────────────┬────────────┬──────────┐
│ alert_id           ┆ node_id            ┆ alert_type        ┆ start_time ┆ end_time   ┆ incident │
│ ---                ┆ ---                ┆ ---               ┆ ---        ┆ ---        ┆ ---      │
│ str                ┆ str                ┆ str               ┆ date       ┆ date       ┆ i32      │
╞════════════════════╪════════════════════╪═══════════════════╪════════════╪════════════╪══════════╡
│ 8be42a49-1f65-4239 ┆ e93e0984-0757-4bef ┆ SOFTWARE_SERVICE_ ┆ 2025-10-10 ┆ 2025-10-10 ┆ 0        │
│ -9f7b-be882a…      ┆ -950a-defe77…      ┆ STATUS_INFO       ┆            ┆            ┆          │
│ 20432fc4-0e73-41d3 ┆ e93e0984-0757-4bef ┆ SOFTWARE_SERVICE_ ┆ 2025-10-10 ┆ 2025-10-10 ┆ 0        │
│ -9567-217826…      ┆ -950a-defe77…      ┆ STATUS_INFO       ┆            ┆            ┆          │
│ e647b6f9-bd2d-4afd ┆ e93e0984-0757-4bef ┆ SOFTWARE_SERVICE_ ┆ 2025-10-10 ┆ 2025-10-10 ┆ 0        │
│ -bcef-3f0afc…      ┆ -950a-defe77…      ┆ STATUS_INFO       ┆            ┆            ┆          │
│ 0e3b5c16-7dae-4519 ┆ e93e0984-0757-4bef ┆ SOFTWARE_SERVICE_ ┆ 2025-10-10 ┆ 2025-10-10 ┆ 0        │
│ -9dd6-2a1711…      ┆ -950a-defe77…      ┆ STATUS_INFO       ┆            ┆            ┆          │
│ afa17fa0-cc4e-48a9 ┆ e93e0984-0757-4bef ┆ SOFTWARE_SERVICE_ ┆ 2025-10-10 ┆ 2025-10-10 ┆ 0        │
│ -b6ea-94c111…      ┆ -950a-defe77…      ┆ STATUS_INFO       ┆            ┆            ┆          │
│ …                  ┆ …                  ┆ …                 ┆ …          ┆ …          ┆ …        │
│ c373a728-5192-4b2b ┆ e93e0984-0757-4bef ┆ SOFTWARE_SERVICE_ ┆ 2025-10-10 ┆ 2025-10-10 ┆ 0        │
│ -9077-5b4a01…      ┆ -950a-defe77…      ┆ STATUS_INFO       ┆            ┆            ┆          │
│ 8c06dd78-048b-48da ┆ e93e0984-0757-4bef ┆ SOFTWARE_SERVICE_ ┆ 2025-10-10 ┆ 2025-10-10 ┆ 0        │
│ -9846-4af411…      ┆ -950a-defe77…      ┆ STATUS_INFO       ┆            ┆            ┆          │
│ 46cc78bb-9563-4af1 ┆ e93e0984-0757-4bef ┆ SOFTWARE_SERVICE_ ┆ 2025-10-10 ┆ 2025-10-10 ┆ 0        │
│ -9cea-2a09f2…      ┆ -950a-defe77…      ┆ STATUS_INFO       ┆            ┆            ┆          │
│ f7301adc-c50c-442b ┆ e93e0984-0757-4bef ┆ SOFTWARE_SERVICE_ ┆ 2025-10-10 ┆ 2025-10-10 ┆ 0        │
│ -a872-4280a8…      ┆ -950a-defe77…      ┆ STATUS_INFO       ┆            ┆            ┆          │
│ 2b7d5b39-6762-4cad ┆ e93e0984-0757-4bef ┆ SOFTWARE_SERVICE_ ┆ 2025-10-10 ┆ 2025-10-10 ┆ 0        │
│ -a838-e7fadc…      ┆ -950a-defe77…      ┆ STATUS_INFO       ┆            ┆            ┆          │
└────────────────────┴────────────────────┴───────────────────┴────────────┴────────────┴──────────┘

In [4]:
from src.utils.node_summary import node_summary
from src.repository.aggregate_results_repository import AggregateResultsRepository

summary, general_metrics = node_summary(graph_repo)

results_repo = AggregateResultsRepository(filename="simple_time_corr_active")
results_repo.save(summary)
results_repo.load()

✅ Nova versão salva com sucesso em: data/results/simple_time_corr_active_20260521_095004.csv
📖 Carregando a versão mais recente encontrada: simple_time_corr_active_20260521_095004.csv

shape: (866, 6)
┌───────────────────────┬──────────┬───────────────┬────────────┬──────────────────────┬───────────┐
│ Node ID               ┆ Total de ┆ Total de      ┆ Total de   ┆ Média de Alarmes por ┆ Densidade │
│ ---                   ┆ Alarmes  ┆ Correlações   ┆ Incidentes ┆ Incidente            ┆ ---       │
│ str                   ┆ ---      ┆ ---           ┆ ---        ┆ ---                  ┆ f64       │
│                       ┆ i64      ┆ i64           ┆ i64        ┆ f64                  ┆           │
╞═══════════════════════╪══════════╪═══════════════╪════════════╪══════════════════════╪═══════════╡
│ c60cc1af-aa30-491a-a3 ┆ 399      ┆ 417           ┆ 130        ┆ 3.069231             ┆ 0.005252  │
│ ef-55c6f8…            ┆          ┆               ┆            ┆                      ┆           │
│ f3ba8721-2bb0-46b3-b4 ┆ 237      ┆ 12358         ┆ 18         ┆ 13.166667            ┆ 0.441894  │
│ dd-c9255b…            ┆          ┆               ┆            ┆                      ┆           │
│ 4c43b243-0774-4296-8f ┆ 57       ┆ 4             ┆ 4          ┆ 14.25                ┆ 0.002506  │
│ 18-85c699…            ┆          ┆               ┆            ┆                      ┆           │
│ 4a278aa6-9cfe-4d85-ae ┆ 60       ┆ 4             ┆ 4          ┆ 15.0                 ┆ 0.00226   │
│ 05-9843e5…            ┆          ┆               ┆            ┆                      ┆           │
│ f02a8eab-0a93-4f87-90 ┆ 60       ┆ 4             ┆ 4          ┆ 15.0                 ┆ 0.00226   │
│ f9-3eb96a…            ┆          ┆               ┆            ┆                      ┆           │
│ …                     ┆ …        ┆ …             ┆ …          ┆ …                    ┆ …         │
│ 3cc6e6d4-a461-4f87-a1 ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ a9-d9d433…            ┆          ┆               ┆            ┆                      ┆           │
│ 781bc011-cb88-42c1-a3 ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ 09-8d1b9b…            ┆          ┆               ┆            ┆                      ┆           │
│ e22ae1c9-4b14-4ebf-bf ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ 4d-1a1103…            ┆          ┆               ┆            ┆                      ┆           │
│ 9d87c815-0b38-49b6-a8 ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ 3a-a8df7a…            ┆          ┆               ┆            ┆                      ┆           │
│ 3f5f8b3a-a920-46d6-b3 ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ a3-9227c7…            ┆          ┆               ┆            ┆                      ┆           │
└───────────────────────┴──────────┴───────────────┴────────────┴──────────────────────┴───────────┘

In [5]:
graph_repo.close()